---

- hosts: all
  become: true
  tasks:
  
  - name: Install Neofetch and BPython
    package:
      name: 
        - "{{ neofetch_package }}"
        - "{{ bpython_package }}"
      state: latest
      update_cache: true
