---

- hosts: all
  become: true
  tasks:
  - name: Install Updates
    apt:
      upgrade: dist
      update_cache: true
    when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:
  - name: Install Apache2
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: db_server
  become: true
  tasks:
  - name: Install MariaDB
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"
